source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

link_with 'SWGradientView_Example', 'MyPlayground'

target 'SWGradientView_Example', :exclusive => true do
  pod "SWGradientView", :path => "../"
end

target 'SWGradientView_Tests', :exclusive => true do
  pod "SWGradientView", :path => "../"

  
end
