source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SWGradientView_Example' do
  pod "SWGradientView", :path => "../"

  target 'SWGradientView_Tests' do
    inherit! :search_paths

  end

end
